[project]
name = "deployment"
version = "0.1.0"
description = "This project provides podman-compose for a local deployment"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "podman-compose>=1.5.0",
]
